name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "pdm.lock"
      - "!mingshe/__version__.py"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "pdm.lock"
      - "!mingshe/__version__.py"

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.9]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: pdm-project/setup-pdm@v2.1
        name: Setup Python and PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 1.8.5
          enable-pep582: true # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: |
          pdm install -v -dG dev -dG test
      - name: Format and type check
        run: |
          python script/check.py
      - name: Test with pytest
        run: |
          pdm run pytest tests -o log_cli=true -o log_cli_level=DEBUG

  publish:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - uses: pdm-project/setup-pdm@v2.1
        name: Setup Python and PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 1.8.5
          enable-pep582: true # Enable PEP 582 package loading globally

      - name: Install dependencies
        run: |
          python -m pip install -U twine

      - name: Build
        run: |
          pdm build

      - name: Publish
        run: |
          twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} --verbose --skip-existing dist/*
